begin;

create schema if not exists private;

do $$
declare
  target_table text;
  sequence_name text;
begin
  foreach target_table in array array[
    'admin_users',
    'categories',
    'products',
    'product_files',
    'sales',
    'sale_files',
    'clients',
    'expenses',
    'promotions',
    'coupons',
    'settings',
    'trash'
  ]
  loop
    if exists (
      select 1
      from information_schema.columns
      where table_schema = 'public'
        and information_schema.columns.table_name = target_table
        and column_name = 'id'
        and is_identity = 'NO'
        and column_default is null
    ) then
      execute format(
        'alter table public.%I alter column id add generated by default as identity',
        target_table
      );
    end if;

    sequence_name := pg_get_serial_sequence(format('public.%I', target_table), 'id');
    if sequence_name is not null then
      execute format(
        'select setval(%L, greatest(coalesce((select max(id) from public.%I), 0), 1), true)',
        sequence_name,
        target_table
      );
    end if;
  end loop;
end
$$;

alter table public.sales
  add column if not exists quantidade integer not null default 1,
  add column if not exists preco_unitario numeric(12, 2) not null default 0,
  add column if not exists custo_unitario numeric(12, 2) not null default 0,
  add column if not exists desconto_valor numeric(12, 2) not null default 0;

update public.sales
set
  quantidade = greatest(coalesce(quantidade, 1), 1),
  preco_unitario = case
    when coalesce(preco_unitario, 0) > 0 then preco_unitario
    else coalesce(valor_venda, 0)
  end,
  custo_unitario = greatest(coalesce(custo_unitario, 0), 0),
  desconto_valor = greatest(coalesce(desconto_valor, 0), 0);

create table if not exists public.admin_login_attempts (
  identifier_hash text primary key,
  attempt_count integer not null default 0,
  window_started_at timestamptz not null default now(),
  blocked_until timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_id integer references public.admin_users(id) on delete set null,
  action text not null,
  resource text not null,
  resource_id text,
  request_id uuid,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.categories
  add column if not exists ativo boolean not null default true;

alter table public.products enable row level security;
alter table public.categories enable row level security;
alter table public.product_files enable row level security;
alter table public.admin_users enable row level security;
alter table public.sales enable row level security;
alter table public.sale_files enable row level security;
alter table public.clients enable row level security;
alter table public.expenses enable row level security;
alter table public.promotions enable row level security;
alter table public.coupons enable row level security;
alter table public.settings enable row level security;
alter table public.trash enable row level security;
alter table public.admin_login_attempts enable row level security;
alter table public.audit_logs enable row level security;

revoke all on public.admin_users from anon, authenticated;
revoke all on public.sales from anon, authenticated;
revoke all on public.sale_files from anon, authenticated;
revoke all on public.clients from anon, authenticated;
revoke all on public.expenses from anon, authenticated;
revoke all on public.promotions from anon, authenticated;
revoke all on public.coupons from anon, authenticated;
revoke all on public.settings from anon, authenticated;
revoke all on public.trash from anon, authenticated;
revoke all on public.admin_login_attempts from anon, authenticated;
revoke all on public.audit_logs from anon, authenticated;
revoke all on public.products from anon, authenticated;
revoke all on public.categories from anon, authenticated;
revoke all on public.product_files from anon, authenticated;

grant select on public.products to anon, authenticated;
grant select on public.categories to anon, authenticated;
grant select on public.product_files to anon, authenticated;
grant all on public.admin_login_attempts to service_role;
grant select, insert on public.audit_logs to service_role;
grant usage, select on sequence public.audit_logs_id_seq to service_role;

drop policy if exists public_active_products on public.products;
create policy public_active_products
  on public.products
  for select
  to anon, authenticated
  using (ativo = true);

drop policy if exists public_active_categories on public.categories;
create policy public_active_categories
  on public.categories
  for select
  to anon, authenticated
  using (ativo = true);

drop policy if exists public_active_product_files on public.product_files;
create policy public_active_product_files
  on public.product_files
  for select
  to anon, authenticated
  using (
    exists (
      select 1
      from public.products
      where products.id = product_files.product_id
        and products.ativo = true
    )
  );

create unique index if not exists admin_users_email_lower_uidx
  on public.admin_users (lower(email));
create unique index if not exists products_codigo_sku_uidx
  on public.products (codigo_sku)
  where codigo_sku is not null and codigo_sku <> '';
create unique index if not exists coupons_codigo_upper_uidx
  on public.coupons (upper(codigo));
create index if not exists products_category_active_idx
  on public.products (category_id, ativo, created_at desc);
create index if not exists products_parent_idx
  on public.products (parent_product_id)
  where parent_product_id is not null;
create index if not exists sales_data_idx
  on public.sales (data_venda desc);
create index if not exists sales_product_idx
  on public.sales (product_id)
  where product_id is not null;
create index if not exists sales_client_idx
  on public.sales (cliente_id)
  where cliente_id is not null;
create index if not exists sales_coupon_idx
  on public.sales (cupom_id)
  where cupom_id is not null;
create index if not exists sales_receivable_idx
  on public.sales (valor_devido)
  where valor_devido > 0;
create index if not exists expenses_date_idx
  on public.expenses (data_gasto desc);
create index if not exists promotions_active_dates_idx
  on public.promotions (ativo, data_inicio, data_fim);
create index if not exists trash_expiration_idx
  on public.trash (expires_at);
create index if not exists audit_logs_actor_date_idx
  on public.audit_logs (actor_id, created_at desc);
create index if not exists audit_logs_resource_idx
  on public.audit_logs (resource, resource_id, created_at desc);

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'sales_quantidade_positive'
  ) then
    alter table public.sales
      add constraint sales_quantidade_positive check (quantidade > 0);
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'sales_values_non_negative'
  ) then
    alter table public.sales
      add constraint sales_values_non_negative check (
        valor_venda >= 0
        and valor_devido >= 0
        and preco_unitario >= 0
        and custo_unitario >= 0
        and desconto_valor >= 0
      );
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'products_stock_non_negative'
  ) then
    alter table public.products
      add constraint products_stock_non_negative check (
        quantidade_estoque >= 0 and estoque_minimo >= 0
      );
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'coupons_usage_non_negative'
  ) then
    alter table public.coupons
      add constraint coupons_usage_non_negative check (
        usos_realizados >= 0
        and (limite_usos is null or limite_usos >= 0)
      );
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'admin_users_role_valid'
  ) then
    alter table public.admin_users
      add constraint admin_users_role_valid check (tipo in ('ADMIN', 'VENDEDOR'));
  end if;
end
$$;

create or replace function public.admin_check_login_rate_limit(
  p_identifier_hash text,
  p_max_attempts integer default 5,
  p_window_minutes integer default 15
)
returns table(allowed boolean, retry_after_seconds integer)
language sql
security invoker
set search_path = ''
as $$
  select
    case
      when attempt.identifier_hash is null then true
      when attempt.window_started_at
        < now() - make_interval(mins => greatest(p_window_minutes, 1))
        then true
      else attempt.attempt_count < greatest(p_max_attempts, 1)
    end as allowed,
    case
      when attempt.identifier_hash is null then 0
      when attempt.window_started_at
        < now() - make_interval(mins => greatest(p_window_minutes, 1))
        then 0
      else greatest(
        0,
        extract(
          epoch from (
            attempt.window_started_at
            + make_interval(mins => greatest(p_window_minutes, 1))
            - now()
          )
        )::integer
      )
    end as retry_after_seconds
  from (select 1) seed
  left join public.admin_login_attempts attempt
    on attempt.identifier_hash = p_identifier_hash;
$$;

create or replace function public.admin_record_login_attempt(
  p_identifier_hash text,
  p_success boolean,
  p_window_minutes integer default 15
)
returns void
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if p_success then
    delete from public.admin_login_attempts
    where identifier_hash = p_identifier_hash;
    return;
  end if;

  insert into public.admin_login_attempts (
    identifier_hash,
    attempt_count,
    window_started_at,
    updated_at
  )
  values (p_identifier_hash, 1, now(), now())
  on conflict (identifier_hash) do update
  set
    attempt_count = case
      when public.admin_login_attempts.window_started_at
        < now() - make_interval(mins => greatest(p_window_minutes, 1))
        then 1
      else public.admin_login_attempts.attempt_count + 1
    end,
    window_started_at = case
      when public.admin_login_attempts.window_started_at
        < now() - make_interval(mins => greatest(p_window_minutes, 1))
        then now()
      else public.admin_login_attempts.window_started_at
    end,
    updated_at = now();
end;
$$;

revoke all on function public.admin_check_login_rate_limit(text, integer, integer)
  from public, anon, authenticated;
revoke all on function public.admin_record_login_attempt(text, boolean, integer)
  from public, anon, authenticated;
grant execute on function public.admin_check_login_rate_limit(text, integer, integer)
  to service_role;
grant execute on function public.admin_record_login_attempt(text, boolean, integer)
  to service_role;

create or replace function public.admin_save_sale(
  p_payload jsonb,
  p_sale_id integer default null
)
returns public.sales
language plpgsql
security invoker
set search_path = ''
as $$
declare
  existing_sale public.sales%rowtype;
  saved_sale public.sales%rowtype;
  selected_product public.products%rowtype;
  selected_coupon public.coupons%rowtype;
  quantity integer := greatest(coalesce((p_payload->>'quantidade')::integer, 1), 1);
  product_id_value integer := nullif(p_payload->>'product_id', '')::integer;
  coupon_id_value integer := nullif(p_payload->>'cupom_id', '')::integer;
  base_value numeric(12, 2) := greatest(coalesce((p_payload->>'valor_venda')::numeric, 0), 0);
  unit_price numeric(12, 2) := greatest(coalesce((p_payload->>'preco_unitario')::numeric, 0), 0);
  unit_cost numeric(12, 2) := greatest(coalesce((p_payload->>'custo_unitario')::numeric, 0), 0);
  discount_value numeric(12, 2) := 0;
  discount_percent numeric(8, 2) := 0;
  final_value numeric(12, 2);
  due_value numeric(12, 2);
begin
  if p_sale_id is not null then
    select * into existing_sale
    from public.sales
    where id = p_sale_id
    for update;

    if not found then
      raise exception 'Venda não encontrada.';
    end if;

    if existing_sale.product_id is not null then
      update public.products
      set quantidade_estoque = quantidade_estoque + greatest(existing_sale.quantidade, 1)
      where id = existing_sale.product_id;
    end if;

    if existing_sale.cupom_id is not null
      and existing_sale.cupom_id is distinct from coupon_id_value then
      update public.coupons
      set usos_realizados = greatest(usos_realizados - 1, 0)
      where id = existing_sale.cupom_id;
    end if;
  end if;

  if product_id_value is not null then
    select * into selected_product
    from public.products
    where id = product_id_value and ativo = true
    for update;

    if not found then
      raise exception 'Produto indisponível.';
    end if;

    if selected_product.quantidade_estoque < quantity then
      raise exception 'Estoque insuficiente para esta venda.';
    end if;

    if unit_price <= 0 then
      unit_price := greatest(coalesce(selected_product.preco_venda, 0), 0);
    end if;
    if unit_cost <= 0 then
      unit_cost := greatest(coalesce(selected_product.custo_total, 0), 0);
    end if;
    if base_value <= 0 then
      base_value := unit_price * quantity;
    end if;
  end if;

  if coupon_id_value is not null then
    select * into selected_coupon
    from public.coupons
    where id = coupon_id_value
    for update;

    if not found
      or not selected_coupon.ativo
      or (
        selected_coupon.data_validade is not null
        and selected_coupon.data_validade < now()
      )
      or (
        selected_coupon.limite_usos is not null
        and selected_coupon.usos_realizados >= selected_coupon.limite_usos
        and (
          p_sale_id is null
          or existing_sale.cupom_id is distinct from coupon_id_value
        )
      ) then
      raise exception 'Cupom inválido, expirado ou esgotado.';
    end if;

    if selected_coupon.categorias is not null
      and product_id_value is not null
      and not (selected_product.category_id = any(selected_coupon.categorias)) then
      raise exception 'Cupom não permitido para a categoria do produto.';
    end if;

    if selected_coupon.tipo_desconto = 'percentual' then
      discount_percent := least(greatest(selected_coupon.valor_desconto, 0), 100);
      discount_value := base_value * discount_percent / 100;
    else
      discount_value := least(greatest(selected_coupon.valor_desconto, 0), base_value);
      discount_percent := case
        when base_value > 0 then discount_value / base_value * 100
        else 0
      end;
    end if;
  end if;

  final_value := greatest(base_value - discount_value, 0);
  due_value := least(
    greatest(coalesce((p_payload->>'valor_devido')::numeric, 0), 0),
    final_value
  );

  if p_sale_id is null then
    insert into public.sales (
      cliente,
      cliente_id,
      item_nome,
      product_id,
      vendedor_id,
      cupom_id,
      desconto_percentual,
      desconto_valor,
      valor_venda,
      valor_devido,
      tipo_pagamento,
      parcelas,
      data_venda,
      lucro,
      observacoes,
      quantidade,
      preco_unitario,
      custo_unitario
    )
    values (
      coalesce(nullif(trim(p_payload->>'cliente'), ''), 'Desconhecido'),
      nullif(p_payload->>'cliente_id', '')::integer,
      coalesce(
        nullif(trim(p_payload->>'item_nome'), ''),
        nullif(selected_product.nome, ''),
        'Item sem nome'
      ),
      product_id_value,
      nullif(p_payload->>'vendedor_id', '')::integer,
      coupon_id_value,
      round(discount_percent, 2),
      round(discount_value, 2),
      round(final_value, 2),
      round(due_value, 2),
      coalesce(nullif(p_payload->>'tipo_pagamento', ''), 'PIX'),
      greatest(coalesce((p_payload->>'parcelas')::integer, 1), 1),
      coalesce((p_payload->>'data_venda')::timestamptz, now()),
      round(final_value - (unit_cost * quantity), 2),
      nullif(p_payload->>'observacoes', ''),
      quantity,
      unit_price,
      unit_cost
    )
    returning * into saved_sale;
  else
    update public.sales
    set
      cliente = coalesce(nullif(trim(p_payload->>'cliente'), ''), 'Desconhecido'),
      cliente_id = nullif(p_payload->>'cliente_id', '')::integer,
      item_nome = coalesce(
        nullif(trim(p_payload->>'item_nome'), ''),
        nullif(selected_product.nome, ''),
        'Item sem nome'
      ),
      product_id = product_id_value,
      vendedor_id = coalesce(
        nullif(p_payload->>'vendedor_id', '')::integer,
        existing_sale.vendedor_id
      ),
      cupom_id = coupon_id_value,
      desconto_percentual = round(discount_percent, 2),
      desconto_valor = round(discount_value, 2),
      valor_venda = round(final_value, 2),
      valor_devido = round(due_value, 2),
      tipo_pagamento = coalesce(nullif(p_payload->>'tipo_pagamento', ''), 'PIX'),
      parcelas = greatest(coalesce((p_payload->>'parcelas')::integer, 1), 1),
      data_venda = coalesce(
        (p_payload->>'data_venda')::timestamptz,
        existing_sale.data_venda
      ),
      lucro = round(final_value - (unit_cost * quantity), 2),
      observacoes = nullif(p_payload->>'observacoes', ''),
      quantidade = quantity,
      preco_unitario = unit_price,
      custo_unitario = unit_cost
    where id = p_sale_id
    returning * into saved_sale;
  end if;

  if product_id_value is not null then
    update public.products
    set quantidade_estoque = quantidade_estoque - quantity
    where id = product_id_value;
  end if;

  if coupon_id_value is not null
    and (
      p_sale_id is null
      or existing_sale.cupom_id is distinct from coupon_id_value
    ) then
    update public.coupons
    set usos_realizados = usos_realizados + 1
    where id = coupon_id_value;
  end if;

  return saved_sale;
end;
$$;

revoke all on function public.admin_save_sale(jsonb, integer)
  from public, anon, authenticated;
grant execute on function public.admin_save_sale(jsonb, integer)
  to service_role;

create or replace function public.admin_delete_sale_to_trash(p_sale_id integer)
returns void
language plpgsql
security invoker
set search_path = ''
as $$
declare
  selected_sale public.sales%rowtype;
begin
  select * into selected_sale
  from public.sales
  where id = p_sale_id
  for update;

  if not found then
    raise exception 'Venda não encontrada.';
  end if;

  insert into public.trash (
    source_store,
    source_id,
    item_name,
    payload,
    expires_at
  )
  values (
    'sales',
    selected_sale.id,
    selected_sale.cliente || ' - ' || selected_sale.item_nome,
    to_jsonb(selected_sale),
    now() + interval '30 days'
  );

  if selected_sale.product_id is not null then
    update public.products
    set quantidade_estoque =
      quantidade_estoque + greatest(selected_sale.quantidade, 1)
    where id = selected_sale.product_id;
  end if;

  if selected_sale.cupom_id is not null then
    update public.coupons
    set usos_realizados = greatest(usos_realizados - 1, 0)
    where id = selected_sale.cupom_id;
  end if;

  delete from public.sales where id = p_sale_id;
end;
$$;

revoke all on function public.admin_delete_sale_to_trash(integer)
  from public, anon, authenticated;
grant execute on function public.admin_delete_sale_to_trash(integer)
  to service_role;

create or replace function public.admin_restore_trash(p_trash_id integer)
returns void
language plpgsql
security invoker
set search_path = ''
as $$
declare
  item public.trash%rowtype;
begin
  select * into item
  from public.trash
  where id = p_trash_id
  for update;

  if not found then
    raise exception 'Item não encontrado na lixeira.';
  end if;

  case item.source_store
    when 'products' then
      insert into public.products
      select (jsonb_populate_record(null::public.products, item.payload)).*;
    when 'sales' then
      insert into public.sales
      select (jsonb_populate_record(null::public.sales, item.payload)).*;
    when 'expenses' then
      insert into public.expenses
      select (jsonb_populate_record(null::public.expenses, item.payload)).*;
    else
      raise exception 'Origem da lixeira não permitida.';
  end case;

  delete from public.trash where id = p_trash_id;
end;
$$;

create or replace function public.admin_purge_expired_trash()
returns integer
language plpgsql
security invoker
set search_path = ''
as $$
declare
  deleted_count integer;
begin
  delete from public.trash where expires_at < now();
  get diagnostics deleted_count = row_count;
  return deleted_count;
end;
$$;

revoke all on function public.admin_restore_trash(integer)
  from public, anon, authenticated;
revoke all on function public.admin_purge_expired_trash()
  from public, anon, authenticated;
grant execute on function public.admin_restore_trash(integer)
  to service_role;
grant execute on function public.admin_purge_expired_trash()
  to service_role;

commit;
